### ISSUE TITLE
Doesn't support unicode and utf characters?

### ISSUE THREAD

**Issue by timstaana** [dzomb/tuneout#3]
The text replaces all the undisplayable characters into ???.

**Comment by Mandybee** [comment]
I know this is 3 years old but you can add a bit to this script to have it write as UTF8:

write this_track **as «class utf8»** to referenceText
write " - " to referenceText
write track_artist **as «class utf8»** to referenceText

**Comment by dzomb** [comment]
Hi @Mandybee - I went and added your suggestion.  Thanks!
